accounts/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib import admin
from .views import get_data

app_name = 'accounts'

urlpatterns = [
    path('', views.indexView, name='index'),
    path('profile/', views.profileView, name = 'profile' ),
    path('login/', LoginView.as_view(), name = 'login_url'), 
    path('register/', views.registerView, name = 'register_url'),
    path('logout/', LogoutView.as_view(next_page='accounts:profile'), name = 'logout'),
    path('caribuku/', views.caribukuView, name='caribuku'),
    path('getData', get_data)
]

bungkusaja/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from feedback import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('accounts.urls', namespace='accounts')),
    path('feedback/', include('feedback.urls')),
]

feedback/urls.py
from django.urls import path
from . import views
from feedback import views

app_name = 'feedback'

urlpatterns = [
    # Untuk forms
    path('review/', views.emp, name='review'),  
    path('',views.show, name='feedback'),
]

webReview/urls.py
from django.urls import path
from . import views
from webReview import views

app_name = 'webReview'

urlpatterns = [
    # Untuk forms
    path('submit/', views.emp, name='submit'),  
    path('',views.show, name='ulasan'),    
    path('delete/<int:id>', views.destroy),
    
]

accounts/models.py
from django.db import models

# Create your models here.

feedback/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

class Responses(models.Model):  
    
    ename = models.CharField(max_length=20)
    emitra = models.CharField(max_length=20)
    ereview = models.CharField(max_length=160)
    erating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    class Meta:  
        db_table = "responses" 

webReview/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

class Data(models.Model):   
    user_name = models.CharField(max_length=20)
    user_email = models.EmailField()
    user_review = models.CharField(max_length=160)
    user_rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    class Meta:  
        db_table = "data" 

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    name = forms.CharField(max_length=30)
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'name', 'email', 'password1', 'password2', )

feedback/forms.py
from django import forms  
from feedback.models import Responses
class ResponsesForm(forms.ModelForm):  
    class Meta:  
        model = Responses 
        fields = "__all__"

webReview/forms.py
from django import forms  
from webReview.models import Data

class DataForm(forms.ModelForm):  
    class Meta:  
        model = Data 
        fields = "__all__"

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.http import JsonResponse

from .forms import SignUpForm #, SignInForm

# Create your views here.
def indexView(request): 
    return render(request, 'index.html')

def caribukuView(request):
    return render(request, 'caribuku.html')
    
def get_data(request):
    key = request.GET['key']
    url = 'https://www.googleapis.com/books/v1/volumes?q=' + key
    response = requests.get(url)
    response_json = response.json()

    return JsonResponse(response_json)

@login_required
def profileView(request):
    return render(request, 'profile.html')

def registerView(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:login_url')
    else:
        form = SignUpForm()

    return render(request, 'registration/register.html', {'form':form})



# def loginView(request):
#     if request.method == 'POST':
#         form = SignInForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('accounts:profile')
    
#     else:
#         form = SignInForm()
    
#     return render(request, 'accounts/login.html', {'form':form})

feedback/views.py
from django.shortcuts import render, redirect  
from feedback.forms import ResponsesForm  
from feedback.models import Responses

from django.core import serializers
from django.http import HttpResponse

import datetime

# TestCase
from django.views.generic import TemplateView

# Create your views here.  
def getData(request):
    Responses = Responses.objects.all()
    Responses_list = serializers.serialize('json', Responses)
    return HttpResponse(Responses_list, content_type="text/json-comment-filtered")

def emp(request):
    form = ResponsesForm()
    if request.method == "POST":  
        form = ResponsesForm(request.POST)  
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('/feedback/review/')  
            except:  
                pass  
    else:  
        form = ResponsesForm()  
    return render(request,'review.html',{'form':form})  

def show(request):  
    responses = Responses.objects.all()  
    return render(request,"feedback.html",{'responses':responses})   

# For TestCase

class ReviewPageView(TemplateView):
    template_name = 'review.html'


class FeedbackPageView(TemplateView):
    template_name = 'feedback.html'

webReview/views.py
from django.shortcuts import render, redirect  
from feedback.forms import DataForm  
from feedback.models import Data

# TestCase
from django.views.generic import TemplateView

# Create your views here.  
def emp(request):  
    if request.method == "POST":  
        form = DataForm(request.POST)  
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('/ulasan/')  
            except:  
                pass  
    else:  
        form = DataForm()  
    return render(request,'submit.html',{'form':form}) 

def show(request):  
    data = Data.objects.all()  
    return render(request,"ulasan.html",{'data':data})  

def destroy(request, id):  
    data = Responses.objects.get(id=id)  
    data.delete()  
    return redirect("/submit/")  

# For TestCase

class SubmitPageView(TemplateView):
    template_name = 'submit.html'


class ReviewsPageView(TemplateView):
    template_name = 'ulasan.html'

accounts/templates/caribuku.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <head>
        <title>bungkusaja caribuku</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'story8.css' %}">
        
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"> </script> 
        <script src="{% static 'story8.js' %}"></script>

        <style>
                table {
                  border-collapse: collapse;
                  width: 100%;
                }
                body{
                  background-color: #FFE4A3;
                }
                
                th, td {
                  text-align: left;
                  padding: 8px;
                }
                
                tr:nth-child(even){background-color: #AB8B74}
                
                th {
                  background-color: #765848;
                  color: white;
                  font-family: montserrat;
                }
                #tombol{
                  margin-bottom: 5%;
                }
                #form{
                  padding-top: 10%;
                }
                #teks{
                  font-family: montserrat;
                  padding-top: 2%;
                }
                .tombol{
                  border-radius: 20%;
                  background-color: #DDBF86;
                  border: #DDBF86;
                  font-family: montserrat;
                }
                .masukan{
                  font-family: montserrat;
                }
            </style>

    </head>
    <title>Test</title>
</head>
<body>
    <h1 class="text-center" id="teks">Cari Buku Yuk!</h1>
    <div class="d-flex justify-content-center align-items-center container " id="form">
        <input type="text" class="form-control-plaintext masukan " placeholder="Search..."> 
    </div>
    <div class="d-flex justify-content-center align-items-center container mt-4" id="tombol">
        <button type="button" class="btn btn-light tombol" id="search">Submit</button>
    </div>
    <div class="container mt-4">
      <table id="tabel">
        <tr>
            <th>Number</th>
            <th>Name</th>
            <th>Author</th>
            <th>Publisher</th>
            <th>Image</th>
        </tr>

        <tbody id="konten">

        </tbody>
    </table>
    </div>
               
</body>
</html>

accounts/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>bungkusaja</title>
    <link href="https://fonts.googleapis.com/css?family=Manjari|Montserrat:300,400,500,600|Poppins:400,600|Pacifico|Open+Sans:300,400,600|Roboto:100,300,400,500,700,900|Monoton&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="icon" href="{% static 'images/logo.png' %}" >
</head>
<body class='background'>
    
    {% block content %}

    <div style="text-align:center;">
        <button class="btn btn-light" name="lightmode" onclick="changeThemeLight()">Tema Terang</button>
        <button class="btn btn-dark" name="darkmode" onclick="changeThemeDark()">Tema Gelap</button>
    </div>
    <div class="textcolour" style="font-family: Montserrat Regular; font-size: 2vh; text-align: center;">
        <div class="container mt-5">
            <div class="text-center p-5">   
            <h2><img src="{% static 'images/logo.png' %}" class="displayed" id="circle"></h2>
            <h2><br></h2>
            <div>
                <h1 style="color: #707070">Selamat Datang</h1>
            </div>

            <a style style="color: #707070; opacity: 100%;" href="{% url 'accounts:caribuku' %}" class="btn-outline-dark btn mt-5">Cari Buku</a>
            <br>

            {% if user.is_authenticated %}
                <a style="color: #707070; opacity: 100%;" href="{% url 'accounts:profile' %}" class="btn-outline-dark btn mt-5">
                    Profil
                </a>
                <br>
                <a style="color: #707070; opacity: 100%;" href="{% url 'accounts:logout' %}" class="btn-outline-dark btn mt-2">
                    Keluar
                </a>
            {% else %}
                <a style="color: #707070; opacity: 100%;" href="{% url 'accounts:login_url' %}" class="btn-outline-dark btn mt-5">
                    Masuk
                </a>
                <br>
                <a style="color: #707070; opacity: 100%;" href="{% url 'accounts:register_url' %}" class="btn-outline-dark btn mt-2">
                    Daftar
                </a>
            {% endif %}
        </div>
    </div>

    <script>
        $(document).ready(function(){
          $("h1").hover(function(){
            $(this).css("color", "#707070");
            }, function(){
            $(this).css("color", "#FE7301");
          });
        });

        function changeThemeLight(){
            $('.background').css('background-color', 'white');
        }

        function changeThemeDark(){
            $('.background').css('background-color', 'black');
        }

        </script>
        
        <script type="text/javascript">
 
            /* In the previous tutorial, we changed an image by clicking on it.
            This time the image will change by itself over time.
            This could be used for an ad banner that changes every few seconds.
            It uses much of the existing code from the previous tutorial.
            */
            
            var image_tracker = 'logo';
            
            function change(){
            var image = document.getElementById('circle');
            if(image_tracker=='logo'){
            image.src='{% static 'images/logo2.png' %}';
            image_tracker='logo2';
            }
            else{
            image.src='{% static 'images/logo.png' %}';
            image_tracker='logo';
            }
            }
            
            // Either the setTimeout() method or the setInterval() method can be used.
            // With the setTimeout() method, it takes two parameters.
            // The first parameter is the code to run, the second parameter is time in milliseconds. 1 sec = 1000 ms.
            // the setTimeout() method only runs once. To repeat, we use the setInterval() method instead.
            // It also uses two parameters, the code to run (or function to use), and the timer interval.
            
            var timer = setInterval('change();',300); 
            
            // this function is called when the onclick event runs. It stops the timer running.
            function stop(){
            clearInterval(timer); //the clearInterval method stops the timer from running
            }
            
            </script>
           


    
    {% endblock %}


</body>
</html>

accounts/templates/profile.html
{% extends 'index.html' %}
{% load static %}


{% block content %}
<div class="container">
<div class="container" position="top" id="navbar">
    <nav class="navbar navbar-expand-lg navbar-light bg-customgrey fixed-top" style="position: absolute; height: 60px; background-color: white; box-shadow: 0px 3px 6px rgba(0, 0, 0, 0.161)">
        <a class="navbar-brand-custom" href=""><img src="{% static 'images/logo.png' %}" height="25vh"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href=""><b>Home</b></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'feedback:review' %}"><b>Review</b></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href=""><b>Mitra</b></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'feedback:feedback' %}"><b>Feedback</b></a>
                </li>
            </ul>
        </div>
    </nav>
</div>

<div class="container mt-5 headline jumbotron" style="background: transparent">
    <div class="p-5 text-center">
        <h1 style="color: #707070; opacity: 100%;" >Hello, <span style='color: black'>{{ user.username }}</span></h1>
        <a style="color: #707070; opacity: 100%; position:center" href="{% url 'accounts:profile' %}" class="btn-outline-dark btn mt-5">Buat Pesanan</a>
        <p><br></p>
        <a style="color: #707070; opacity: 100%; position: center" href="{% url 'accounts:login_url' %}" class="btn-outline-dark btn mt-5">Keluar</a>
    </div>
</div>
</div>
{% endblock %}

feedback/templates/feedback.html
{% extends 'templates/base.html' %}
{% load static %}

{% block style %}
<!-- style goes here! -->
{% endblock %}

{% block script %}
    <link rel="stylesheet" href="{% static 'static/jquery.js' %}">
    <!-- additional scripts goes here! -->
{% endblock %}


{% block content %}

<div class="container" id="testi" style="margin-top: 100px; text-align: left">
    <h1>Testimoni</h1>
</div>
    <div class=middle-confirmed style="display: flex; justify-content: center;">
        <table class="table table-striped table-bordered table-sm" align="center" style="align-self: center; width: 75%;">  
            <thead class="thead-choco">   
                <tr>
                    <th>Reviewer</th>  
                    <th>Mitra</th>  
                    <th>Review</th>  
                    <th>Rating</th>
                </tr>  
            </thead>  
            <tbody>  
                {% for responses in responses %}  
                <tr>  
                    <td>{{ responses.ename }}</td>
                    <td>{{ responses.emitra }}</td>  
                    <td>{{ responses.ereview }}</td>
                    <td>{{ responses.erating }}</td>
                </tr>  
            {% endfor %}  
            </tbody>  
        </table>  
    </div>
<br>  
<br>

<button class="accordion">Thank you!</button>
<div class="panel">
    <p style="color:black">We hope your feedback will make us be better in the future!</p>
</div>

<script>
    var acc = document.getElementsByClassName("accordion");
    var i;

    for (i = 0; i < acc.length; i++) {
        acc[i].addEventListener("click", function() {
            this.classList.toggle("active");
            var panel = this.nextElementSibling;
            if (panel.style.maxHeight) {
                panel.style.maxHeight = null;
            } else {
                panel.style.maxHeight = panel.scrollHeight + "px";
            } 
        });
    }
</script>

<script>
        $(document).ready(function(){
          $("h1").hover(function(){
            $(this).css("color", "#707070");
            }, function(){
            $(this).css("color", "#FE7301");
          });
        });
</script>

<h2><img src="{% static 'images/food1.png' %}" class="displayed" id="circle"></h2>
<script type="text/javascript">

            var image_tracker = 'food1';
            
            function change(){
            var image = document.getElementById('circle');
            if(image_tracker=='food1'){
            image.src='{% static 'images/food2.png' %}';
            image_tracker='food2';
            }
            else{
            image.src='{% static 'images/food1.png' %}';
            image_tracker='food1';
            }
            }
            var timer = setInterval('change();',1500); 
            
            // this function is called when the onclick event runs. It stops the timer running.
            function stop(){
            clearInterval(timer); //the clearInterval method stops the timer from running
            }
            
            </script>

<link rel="icon" href="{% static 'images/logo.png' %}" >
{% endblock %}
    

feedback/templates/review.html
{% extends 'templates/base.html' %}
{% load static %}

{% block style %}
{% endblock %}

{% block script %}
<!-- additional scripts goes here! -->
{% endblock %}


{% block content %}
<div class="container" position="relative">
<form method="POST" class="post-form" action="/feedback/review/">  
    {% csrf_token %}
    <center>
        <div class="container" id="middle-assurance" style="margin-top: 60px;">  
            <br>  
            <div class="form-group row" style="display: flex; justify-content: center;">  
                <label class="col-sm-1 col-form-label"></label>  
                <div class="col-sm-4">  
                    <h3>Testimoni</h3>  
                </div>  
            </div>  
            <div class="form-group row" style="display: flex; justify-content: center;">  
                <label class="col-sm-2 col-form-label">Namamu:</label>  
                <div class="col-sm-4">  
                    {{ form.ename  }} 
                </div>  
            </div>  
            <div class="form-group row" style="display: flex; justify-content: center;">  
                <label class="col-sm-2 col-form-label">Mitra Pesanan:</label>  
                <div class="col-sm-4">  
                    {{ form.emitra }}  
                </div>  
            </div>  
            <div class="form-group row" style="display: flex; justify-content: center;">  
                <label class="col-sm-2 col-form-label">Review:</label>  
                <div class="col-sm-4">  
                    {{ form.ereview }}  
                </div>  
            </div>  
            <div class="form-group row" style="display: flex; justify-content: center;">  
                <label class="col-sm-2 col-form-label">Rating:</label>  
                <div class="col-sm-4">  
                    {{ form.erating }}  
                </div>  
            </div>
            <div class="form-group row" style="display: flex; justify-content: center;">  
                <label class="col-sm-1 col-form-label"></label>  
                <div class="col-sm-4">  
                    <button type="submit" class="btn btn-primary">Kirim</button>  
                </div>  
            </div>
        </div>  
    </center>
</form>
</div>


{% endblock %}
    

templates/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">

        <!-- Bootstrap core CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Manjari|Montserrat:300,400,500,600|Poppins:400,600|Pacifico|Open+Sans:300,400,600|Roboto:100,300,400,500,700,900|Monoton&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>


        <!-- Custom styles for this template -->
        <!-- <link href="{% static 'css/style.css' %}" rel="stylesheet"> -->
        <!-- Style for footer -->
        <style>
        .footer {
            position: fixed;
            left: 0;
            bottom: 0;
            width: 100%;
            background-color: white;
            color: white;
            text-align: center;
        }
        </style>
    </head>
    
    <body id="navbar">
    
        <div class="container">
            <div class="container" position="top" id="navbar">
                <nav class="navbar navbar-expand-lg navbar-light bg-customgrey fixed-top" style="position: absolute; height: 60px; background-color: white; box-shadow: 0px 3px 6px rgba(0, 0, 0, 0.161)">
                    <a class="navbar-brand-custom" href=""><img src="https://i.imgur.com/zxHvbHY.png" height="25vh"></a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarResponsive">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="nav-link" href=""><b>Home</b></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'feedback:review' %}"><b>Review</b></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href=""><b>Profil</b></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'feedback:feedback' %}"><b>Feedback</b></a>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
    
            <!-- Content -->
            {% block content %}
            {% endblock content %}
        </div>
    </body>
</html>

<script>
    window.addEventListener('scroll', () => {
   let children = parent.getElementsByTagName('div');
   for(let i = 0; i < children.length; i++) {
     children[i].style.transform = 'translateY(-' + (window.pageYOffset * i / children.length) + 'px)';
   }
}, false)</script>

webReview/templates/submit.html
{% extends 'templates/base.html' %}
{% load static %}

{% block style %}
<!-- style goes here! -->
{% endblock %}

{% block content %}
<div>
	<form method="POST"action="{% url 'webReview:ulasan' %}" class="container m-auto"> <!-- need an action-->
		{% csrf_token %}
		<div class="form-group row justify-content-center padding">
			<div class="col-1">
				<label for="exampleInputNama"> Nama: </label>
			</div>
			<div class="col-4">
				{{ form.user_name }} 
			</div>
		</div>
		<div class="form-group row justify-content-center">
			<div class="col-1">
				<label for="exampleInputNama"> Email: </label>
			</div>
			<div class="col-4">
				{{ form.user_email }}
			</div>
		</div>
		<div class="form-group row justify-content-center">
			<div class="col-1">
				<label for="exampleInputNama"> Review: </label>
			</div>
			<div class="col-4">
				{{ form.user_review }}
			</div>
		</div>
		<div class="form-group row justify-content-center">
			<div class="col-1">
				<label for="exampleInputNama"> Rating: </label>
			</div>
			<div class="col-4">
				{{ form.user_rating }}
			</div>
		</div>
		<div class="row justify-content-center padding">
				<input type="submit" value="Submit">
		</div>
	</form>
</div>
{% endblock %}
    
{% block script %}
<!-- additional scripts goes here! -->
{% endblock %}

webReview/templates/ulasan.html
{% extends 'templates/base.html' %}
{% load static %}

{% block style %}
<!-- style goes here! -->
{% endblock %}

{% block content %}
<div class="container" id="testi" style="margin-top: 100px; text-align: left">
    <h1>Rating dan Ulasan</h1>
</div>
    <div class=middle-confirmed style="display: flex; justify-content: center;">
        <table class="table table-striped table-bordered table-sm" align="center" style="align-self: center; width: 75%;">  
            <thead class="thead-choco">   
                <tr>
                    <th>Reviewer</th>  
                    <th>E-mail</th>  
                    <th>Review</th>  
                    <th>Rating</th>  
                    <th>Action</th>  
                </tr>  
            </thead>  
            <tbody>  
                {% for data in data %}  
                <tr>  
                    <td>{{ data.user_name }}</td>  
                    <td>{{ data.user_email }}</td>  
                    <td>{{ data.user_review }}</td>
                    <td>{{ data.user_rating }}</td> 
                    <td>  <a href="/delete/{{ data.id }}">Delete</a>  </td>  
                </tr>  
            {% endfor %}  
            </tbody>  
        </table>  
    </div>
    <div class=middle-confirmed style="display: flex; justify-content: center;">
    	<button href="{% url 'webReview:submit' %}" class="btn btn-primary">Tambah Ulasan</button>  
    </div>
<br>  
<br>   
{% endblock %}
    
{% block script %}
<!-- additional scripts goes here! -->
{% endblock %}